# 5. Fayldan oʻqish va unga yozish. HDF5
**Bu vazifalarni bajargach, CSV, Excel va HDF5 formatlarida fayllarni oʻqish hamda saqlash, yaʼni data processing (ma’lumotlarga ishlov berish) koʻnikmasini oʻzlashtirasiz.**


#1-topshiriq


1.    Quyidagi link orqali maʼlumotlarni Pandas dataframeʼiga yuklab oling.
    
  *   https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv



2.   Yuklab olingan maʼlumotlarni `aqi.csv` fayliga saqlang.

3. Saqlab olingan `aqi.csv` faylining oxirgi 5 ta qatorini oʻqing.

Eslatma: fayl nomini `aqi.csv` deb saqlaganimizning sababi AQI – Air Quality Index, yaʼni havo sifati indeksi deganidir. Bizning maʼlumotlarimizda davlatlarning havo sifati haqidagi maʼlumotlar saqlangan!

In [100]:
# 1. Quyidagi link orqali ma'lumotlarni Pandas dataframe'iga yuklab olamiz
import pandas as pd
url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv"
aqi = pd.read_csv(url)
aqi

,Date,Country,Status,AQI Value
0,2022-07-21,Albania,Good,14
1,2022-07-21,Algeria,Moderate,65
2,2022-07-21,Andorra,Moderate,55
3,2022-07-21,Angola,Unhealthy for Sensitive Groups,113
4,2022-07-21,Argentina,Moderate,63
...,...,...,...,...
18116,2025-03-06,United States of America,Moderate,82
18117,2025-03-06,Uzbekistan,Good,17
18118,2025-03-06,Vatican,Moderate,65
18119,2025-03-06,Venezuela,Good,11
18120,2025-03-06,Vietnam,Moderate,64

In [101]:
# 1.1 Yuklab olingan ma'lumotlarni aqi.csv fayliga saqlash.
aqi.to_csv('aqi.csv', index=False)

In [102]:
# 1.2 Saqlab olingan aqi.csv faylining oxirgi 5 ta qatorini o'qish
aqidf = pd.read_csv('aqi.csv', nrows=5)

#2-topshiriq
1. Saqlab olingan `aqi.csv` faylidagi maʼlumotlarning faqat 2024-yilga tegishlisini excel faylga `aqi_2024.xlsx` koʻrinishida saqlab oling.
2. Saqlab olingan `aqi_2024.xlsx` faylidan Oʻzbekistonga tegishli maʼlumotni (qatorlarni) oʻqing.

In [103]:
# 2. aqi.csv faylini chaqirib olamiz
aqidf = pd.read_csv('aqi.csv')

In [104]:
# 2.1 'Date' ustunini datetime formatiga o'tkazib olamiz (bu keyinchalik str qiymat bo'lib ma'lumotlarni filtrlashda konflikt bermaslik uchun)
aqidf['Date'] = pd.to_datetime(aqidf['Date'])

In [105]:
# 2.2 ma'lumotlarni filtrlash va joriy qilish
aqidf['Date'].dt.year == 2024 # faqat 2024-yildagi ma'lumotlarni qoldirish
aqi2024 = aqidf[aqidf['Date'].dt.year == 2024] # natijani DF ga joriy qilish
aqi2024

,Date,Country,Status,AQI Value
12986,2024-06-06,Albania,Good,17
12987,2024-06-06,Algeria,Good,46
12988,2024-06-06,Andorra,Moderate,51
12989,2024-06-06,Argentina,Moderate,52
12990,2024-06-06,Armenia,Good,26
...,...,...,...,...
16892,2024-12-26,United States of America,Unhealthy for Sensitive Groups,109
16893,2024-12-26,Uzbekistan,Moderate,98
16894,2024-12-26,Vatican,Good,23
16895,2024-12-26,Venezuela,Good,33
16896,2024-12-26,Vietnam,Moderate,73

In [106]:
# 2.3 aqi_2024.xlsx (excel) ko'rinishida saqlab olish
aqi2024.to_excel('aqi_2024.xlsx')

In [107]:
# 2.4 aqi_2024.xlsx faylidan O'zbekistonga tegishli ma'lumot (qatorlar)ni filtrlash
uzaqi2024 = pd.read_excel('aqi_2024.xlsx')
uzaqi2024 = uzaqi2024[uzaqi2024['Country'] == 'Uzbekistan']
uzaqi2024.head(10)

      Unnamed: 0       Date     Country Status  AQI Value
128        13114 2024-06-06  Uzbekistan   Good         21
261        13247 2024-06-06  Uzbekistan   Good         21
394        13380 2024-06-13  Uzbekistan   Good         35
525        13511 2024-06-20  Uzbekistan   Good         10
656        13642 2024-06-27  Uzbekistan   Good         26
786        13772 2024-07-04  Uzbekistan   Good         19
914        13900 2024-07-11  Uzbekistan   Good         26
1043       14029 2024-07-18  Uzbekistan   Good         42
1173       14159 2024-07-25  Uzbekistan   Good         30
1302       14288 2024-08-01  Uzbekistan   Good         45

#3-topshiriq
1. `aqi.csv` faylidagi maʼlumotlarni oʻrganib chiqsangiz, bu faylda 2022–2025-yillar oraligʻidagi havo sifati haqidagi maʼlumotlarni koʻrishingiz mumkin. Hozir sizga vazifa:
  * `aqi_2022.csv`, `aqi_2023.csv`, `aqi_2024.csv`, `aqi_2025.csv`  fayllariga `aqi.csv` faylidagi maʼlumotlarning mos davrlarini saqlang. Misol uchun, `aqi_2022` fayli 2022-yildagi havo sifati haqidagi maʼlumotlarni oʻzida saqlaydi.

In [108]:
# 3. AQI 2022 ma'lumotlarini csv faylga yozish
aqidf['Date'].dt.year == 2022
aqi2022 = aqidf[aqidf['Date'].dt.year == 2022]
aqi2022.to_csv('aqi_2022.csv')

In [109]:
# 3.1 AQI 2023 ma'lumotlarini csv faylga yozish
aqidf['Date'].dt.year == 2023
aqi2023 = aqidf[aqidf['Date'].dt.year == 2023]
aqi2023.to_csv('aqi_2023.csv')

In [110]:
# 3.2 AQI 2024 ma'lumotlarini csv faylga yozish
aqidf['Date'].dt.year == 2024
aqi2024 = aqidf[aqidf['Date'].dt.year == 2024]
aqi2024.to_csv('aqi_2024.csv')

In [111]:
# 3.3 AQI 2025 ma'lumotlarini csv faylga yozish
aqidf['Date'].dt.year == 2025
aqi2025 = aqidf[aqidf['Date'].dt.year == 2025]
aqi2025.to_csv('aqi_2025.csv')

#4-topshiriq
1. Saqlab olingan `aqi_2022.csv`, `aqi_2023.csv`, `aqi_2024.csv`, `aqi_2025.csv`  fayllarini HDF5 formatida saqlang. Fayl nomini `aqi.h5` deb nomlang. Kalit (key) sifatida fayllarning yillarini bering. Misol uchun, key=2025.

In [112]:
# 4. HDF5 fayl yaratib olish
hdfaqi = pd.HDFStore("aqi.h5")

In [113]:
# 4.1 Kalit (key) sifatida fayllarning yillarini berish

hdfaqi.put('aqi2022', aqi2022)
hdfaqi.put('aqi2023', aqi2023)
hdfaqi.put('aqi2024', aqi2024)
hdfaqi.put('aqi2025', aqi2025)

hdfaqi.keys()

['/Date', '/aqi2022', '/aqi2023', '/aqi2024', '/aqi2025']

#5-topshiriq
1. `aqi.h5` faylidan maʼlumotlarni oʻqing va 2025-yilga tegishli maʼlumotlarni yangi dataframeʼga saqlang.
2. `aqi.h5` faylida 2025-yilning qaysi oylari uchun maʼlumotlar bor? Shu oylar roʻyxatini ekranga chiqaring!

In [114]:
# 5. aqi.h5 falidan ma'lumotlarni o'qish va aqi25 df ga saqlash
aqi25 = hdfaqi['aqi2025']
aqi25.sample(10)

,Date,Country,Status,AQI Value
17440,2025-01-30,Israel,Moderate,85
17089,2025-01-09,Macao,Unhealthy for Sensitive Groups,129
17182,2025-01-16,Ghana,Moderate,97
17748,2025-02-13,Ukraine,Unhealthy for Sensitive Groups,118
18104,2025-03-06,Switzerland,Moderate,57
16939,2025-01-02,Guatemala,Moderate,53
17434,2025-01-30,Iceland,Good,20
18112,2025-03-06,Uganda,Unhealthy,177
17477,2025-01-30,Peru,Unhealthy for Sensitive Groups,139
17994,2025-02-27,United States of America,Moderate,96

In [115]:
# 5.1 aqi.h5 faylida 2025-yilning oy (Month) ma'lumotlarini ekranga chiqarish
aqi25['Month'] = aqi25['Date'].dt.month_name()
aqi25['Month'].unique()

array(['January', 'February', 'March'], dtype=object)