#**10-modul. Maʼlumotlarga ishlov berish. Fayllar va maʼlumotlar ombori**
#10.11. Veb sahifalardan oʻqish. JSON va API
**Bu vazifalarni bajargach, veb sahifalardan maʼlumot olish, JSON bilan ishlash va API soʻrovlarini yuborish koʻnikmalarini egallaysiz.**

In [101]:
import pandas as pd
import requests
from io import StringIO
from IPython.display import display

#1-topshiriq
1. Pandas kutubxonasidan foydalanib, quyida berilgan link ichidan barcha jadvallarni o‘qing va roʻyxat shaklida saqlang.

Link 403 Forbidden (Manzil to'g'ri, lekin kirish taqiqlangan.) xatoligini bermasligi uchun, sahifani avval requests bilan yuklab, keyin pd.read_html() ga HTML matnini bering.

 * https://en.wikipedia.org/wiki/Fossil_fuel_exporters
2. Har bir jadvalning birinchi 1 qatorini ekranga chiqaring.

In [102]:
# 1. berilgan link ichidan barcha jadvallarni o'qish
url = "https://en.wikipedia.org/wiki/Fossil_fuel_exporters"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"} # Wikipedia so'rovni oddiy brauzerdan kelmoqda deb o'ylashi uchun User-Agent beramiz
response = requests.get(url, headers=headers) # web-sahifaga so'rov yuborish
data = pd.read_html(StringIO(response.text)) # HTML tarkibidan jadvallarni o'qib olish
data[1]

,Rank,Country/region,Oil - exports,Date of information
0,1,Saudi Arabia,"6,658,642 bbl/d (1,058,639.5 m3/d)",2020 est.
1,2,Russia,"4,653,500 bbl/d (739,850 m3/d)",2020 est.
2,3,Iraq,"3,428,379 bbl/d (545,068.7 m3/d)",2020 est.
3,4,Canada,"3,037,668 bbl/d (482,950.6 m3/d)",2020
4,5,Iran,"2,700,000 bbl/d (430,000 m3/d)",2021 est.
5,6,United Arab Emirates,"2,418,388 bbl/d (384,493.0 m3/d)",2020
6,7,Nigeria,"1,879,288 bbl/d (298,782.9 m3/d)",2020
7,8,Kuwait,"1,826,331 bbl/d (290,363.4 m3/d)",2020
8,9,Norway,"1,501,768 bbl/d (238,762.0 m3/d)",2020
9,10,Kazakhstan,"1,410,917 bbl/d (224,317.9 m3/d)",2019 est.

In [103]:
# 1.2  Har bir jadvalning tartib raqami va 1-qatorini chiqarish
for i, table in enumerate(data):
    print(f"{i+1}-jadval")
    display(table.head(1))

1-jadval

    0                                                  1
0 NaN  This article needs to be updated. Please help ...

2-jadval

   Rank Country/region                       Oil - exports Date of information
0     1   Saudi Arabia  6,658,642 bbl/d (1,058,639.5 m3/d)           2020 est.

3-jadval

   Rank Country/region  Natural gas - exports (cu m) Date of information
0     1         Russia                  199928345000           2020 est.

4-jadval

   Rank    Country  Coal - exports (thousand short tons)  Date of information
0     1  Indonesia                                451520                 2020

5-jadval

,vteLists of countries by energy rankings,vteLists of countries by energy rankings.1
0,Fossil Fuel,Petroleum All Production Consumption Exports I...

6-jadval

           0                                                  1
0  Petroleum  All Production Consumption Exports Imports Res...

7-jadval

         0                                   1
0  Uranium  All Production Generation Reserves

#2-topshiriq
Yuqorida yaratilgan jadvallar roʻyxatidan eng uzunini `largest_data.csv` fayliga saqlang.

In [104]:
# 2. jadvallar ro'yxatidan eng uzunini largest_data.csv fayliga saqlash
data[4].to_csv('largest_data.csv')

#3-topshiriq
1. Quyidagi link orqali json maʼlumotni yuklab oling va uni climate_change_co2.json nomi bilan saqlang.
 * https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/json_data.json
2. Maʼlumotlar boshidan 5 ta qatorni ekranga chiqaring!

In [105]:
# 3. berilgan url manzildan json ma'lumotlarni olish
url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/json_data.json"
co2 = pd.read_json(url) # url dan kelgan json formatdagi ma'lumotlarni o'zgaruvchiga saqlash
co2.to_json('climate_change_co2.json') # o'zgaruvchidagi ma'lumotni json faylga saqlash
co2.head(5)

,Year,Total,Gas Fuel,Liquid Fuel,Solid Fuel,Cement,Gas Flaring,Per Capita
0,2010,9167,1702,3114,3842,450,59,1.33
1,2009,8740,1585,3056,3620,413,66,1.28
2,2008,8783,1631,3122,3571,388,71,1.30
3,2007,8566,1572,3081,3464,382,68,1.28
4,2006,8370,1525,3089,3339,356,61,1.27

#4-topshiriq
1. Quyida berilgan linkga `get` soʻrovini yuborish orqali `json` maʼlumotlarini `posts.json` fayliga saqlang.
  * https://jsonplaceholder.typicode.com/posts/
2. Ushbu maʼlumotlarni dataframe koʻrinishida saqlang va tasodifiy 5 ta qatorni ekranga chiqaring.

In [106]:
url = "https://jsonplaceholder.typicode.com/posts/"
response = requests.get(url) # url manzildagi json faylga o'tish
df = pd.DataFrame(response.json()) #kelgan json m'alumotlarni DataFrame ga olamiz
df.to_json("posts.json") # ma'lumotlarni json faylga yozamiz

In [107]:
df2 = pd.read_json('posts.json') # json falyni o'qish
df2.sample(5) # 5 ta tasodify qatorni chiqarish

,userId,id,title,body
37,4,38,explicabo et eos deleniti nostrum ab id repell...,animi esse sit aut sit nesciunt assumenda eum ...
11,2,12,in quibusdam tempore odit est dolorem,itaque id aut magnam\npraesentium quia et ea o...
64,7,65,consequatur id enim sunt et et,voluptatibus ex esse\nsint explicabo est aliqu...
44,5,45,ut numquam possimus omnis eius suscipit laudan...,est natus reiciendis nihil possimus aut provid...
58,6,59,qui commodi dolor at maiores et quis id accusa...,perspiciatis et quam ea autem temporibus non v...