# 5. Fayldan oʻqish va unga yozish. HDF5
**Bu vazifalarni bajargach, CSV, Excel va HDF5 formatlarida fayllarni oʻqish hamda saqlash, yaʼni data processing (ma’lumotlarga ishlov berish) koʻnikmasini oʻzlashtirasiz.**


#1-topshiriq


1.    Quyidagi link orqali maʼlumotlarni Pandas dataframeʼiga yuklab oling.
    
  *   https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv



2.   Yuklab olingan maʼlumotlarni `aqi.csv` fayliga saqlang.

3. Saqlab olingan `aqi.csv` faylining oxirgi 5 ta qatorini oʻqing.

Eslatma: fayl nomini `aqi.csv` deb saqlaganimizning sababi AQI – Air Quality Index, yaʼni havo sifati indeksi deganidir. Bizning maʼlumotlarimizda davlatlarning havo sifati haqidagi maʼlumotlar saqlangan!

In [3]:
# 1. Quyidagi link orqali ma'lumotlarni Pandas dataframe'iga yuklab olamiz
import pandas as pd
url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv"
aqi = pd.read_csv(url)
aqi

,Date,Country,Status,AQI Value
0,2022-07-21,Albania,Good,14
1,2022-07-21,Algeria,Moderate,65
2,2022-07-21,Andorra,Moderate,55
3,2022-07-21,Angola,Unhealthy for Sensitive Groups,113
4,2022-07-21,Argentina,Moderate,63
...,...,...,...,...
18116,2025-03-06,United States of America,Moderate,82
18117,2025-03-06,Uzbekistan,Good,17
18118,2025-03-06,Vatican,Moderate,65
18119,2025-03-06,Venezuela,Good,11
18120,2025-03-06,Vietnam,Moderate,64

In [10]:
# 2. Yuklab olingan ma'lumotlarni aqi.csv fayliga saqlash.
aqi.to_csv('aqi.csv')

In [18]:
# 3. Saqlab olingan aqi.csv faylining oxirgi 5 ta qatorini o'qish
aqidf = pd.read_csv('aqi.csv', nrows=5)

#2-topshiriq
1. Saqlab olingan `aqi.csv` faylidagi maʼlumotlarning faqat 2024-yilga tegishlisini excel faylga `aqi_2024.xlsx` koʻrinishida saqlab oling.
2. Saqlab olingan `aqi_2024.xlsx` faylidan Oʻzbekistonga tegishli maʼlumotni (qatorlarni) oʻqing.

In [38]:
# 1.0 aqi.csv faylini chaqirib olamiz
aqidf = pd.read_csv('aqi.csv')

In [40]:
# 1.1 'Date' ustunini datetime formatiga o'tkazib olamiz (bu keyinchalik str qiymat bo'lib ma'lumotlarni filtrlashda konflikt bermaslik uchun)
pd.to_datetime(aqidf['Date'])

0       2022-07-21
1       2022-07-21
2       2022-07-21
3       2022-07-21
4       2022-07-21
           ...
18116   2025-03-06
18117   2025-03-06
18118   2025-03-06
18119   2025-03-06
18120   2025-03-06
Name: Date, Length: 18121, dtype: datetime64[ns]

In [48]:
# 1.2 ma'lumotlarni filtrlash va joriy qilish
aqidf['Date'].dt.year == 2024 # faqat 2024-yildagi ma'lumotlarni qoldirish
aqi2024 = aqidf[aqidf['Date'].dt.year == 2024] # natijani DF ga joriy qilish
aqi2024

,Unnamed: 0,Date,Country,Status,AQI Value
12986,12986,2024-06-06,Albania,Good,17
12987,12987,2024-06-06,Algeria,Good,46
12988,12988,2024-06-06,Andorra,Moderate,51
12989,12989,2024-06-06,Argentina,Moderate,52
12990,12990,2024-06-06,Armenia,Good,26
...,...,...,...,...,...
16892,16892,2024-12-26,United States of America,Unhealthy for Sensitive Groups,109
16893,16893,2024-12-26,Uzbekistan,Moderate,98
16894,16894,2024-12-26,Vatican,Good,23
16895,16895,2024-12-26,Venezuela,Good,33
16896,16896,2024-12-26,Vietnam,Moderate,73

In [ ]:
# 1.3

#3-topshiriq
1. `aqi.csv` faylidagi maʼlumotlarni oʻrganib chiqsangiz, bu faylda 2022–2025-yillar oraligʻidagi havo sifati haqidagi maʼlumotlarni koʻrishingiz mumkin. Hozir sizga vazifa:
  * `aqi_2022.csv`, `aqi_2023.csv`, `aqi_2024.csv`, `aqi_2025.csv`  fayllariga `aqi.csv` faylidagi maʼlumotlarning mos davrlarini saqlang. Misol uchun, `aqi_2022` fayli 2022-yildagi havo sifati haqidagi maʼlumotlarni oʻzida saqlaydi.

In [7]:
#javobni shu yerda yozing.

#4-topshiriq
1. Saqlab olingan `aqi_2022.csv`, `aqi_2023.csv`, `aqi_2024.csv`, `aqi_2025.csv`  fayllarini HDF5 formatida saqlang. Fayl nomini `aqi.h5` deb nomlang. Kalit (key) sifatida fayllarning yillarini bering. Misol uchun, key=2025.

In [8]:
#javobni shu yerda yozing.

#5-topshiriq
1. `aqi.h5` faylidan maʼlumotlarni oʻqing va 2025-yilga tegishli maʼlumotlarni yangi dataframeʼga saqlang.
2. `aqi.h5` faylida 2025-yilning qaysi oylari uchun maʼlumotlar bor? Shu oylar roʻyxatini ekranga chiqaring!

In [9]:
#javobni shu yerda yozing.