In [ ]:
import pandas as pd
import sqlite3 as sql

In [ ]:
db = sql.connect("new.db")
cursor = db.cursor()

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/Electricity_Production_By_Source.csv")
df.head(5)

,Entity,Code,Year,Electricity from coal (TWh),Electricity from gas (TWh),Electricity from hydro (TWh),Electricity from other renewables (TWh),Electricity from solar (TWh),Electricity from oil (TWh),Electricity from wind (TWh),Electricity from nuclear (TWh)
0,Afghanistan,AFG,2000,0.0,0.155,0.312,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.0,0.094,0.498,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.0,0.132,0.555,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.0,0.309,0.630,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.0,0.329,0.565,0.0,0.0,0.0,0.0,0.0

In [ ]:
cols = ['country', 'code', 'year', 'coal', 'gas', 'hydro', 'renewable_other', 'solar', 'oil', 'wind', 'nuclear']
df.columns = cols

In [ ]:
df.to_sql('elect', db)

6241

In [ ]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('elect',)]

In [ ]:
cursor.execute("PRAGMA table_info(elect);")
cursor.fetchall()

[(0, 'index', 'INTEGER', 0, None, 0),
 (1, 'country', 'TEXT', 0, None, 0),
 (2, 'code', 'TEXT', 0, None, 0),
 (3, 'year', 'INTEGER', 0, None, 0),
 (4, 'coal', 'REAL', 0, None, 0),
 (5, 'gas', 'REAL', 0, None, 0),
 (6, 'hydro', 'REAL', 0, None, 0),
 (7, 'renewable_other', 'REAL', 0, None, 0),
 (8, 'solar', 'REAL', 0, None, 0),
 (9, 'oil', 'REAL', 0, None, 0),
 (10, 'wind', 'REAL', 0, None, 0),
 (11, 'nuclear', 'REAL', 0, None, 0)]

In [ ]:
query = "SELECT * FROM elect WHERE country='Uzbekistan' LIMIT 10"
pd.read_sql(query, db)

,index,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
0,5964,Uzbekistan,UZB,2000,11.602405,25.523451,5.817,0.0,0.0,1.380143,0.0,0.0
1,5965,Uzbekistan,UZB,2001,11.766320,25.884038,5.899,0.0,0.0,1.399642,0.0,0.0
2,5966,Uzbekistan,UZB,2002,12.214374,26.869686,6.124,0.0,0.0,1.452939,0.0,0.0
3,5967,Uzbekistan,UZB,2003,11.833513,26.031852,7.544,0.0,0.0,1.407634,0.0,0.0
4,5968,Uzbekistan,UZB,2004,11.595776,25.508869,8.920,0.0,0.0,1.379355,0.0,0.0
5,5969,Uzbekistan,UZB,2005,11.490919,25.278199,8.838,0.0,0.0,1.366882,0.0,0.0
6,5970,Uzbekistan,UZB,2006,11.827788,26.019258,4.653,0.0,0.0,1.406953,0.0,0.0
7,5971,Uzbekistan,UZB,2007,12.051665,26.511751,4.610,0.0,0.0,1.433584,0.0,0.0
8,5972,Uzbekistan,UZB,2008,10.774273,23.701692,4.443,0.0,0.0,1.281634,0.0,0.0
9,5973,Uzbekistan,UZB,2009,9.084625,28.017530,6.418,0.0,0.0,1.080645,0.0,0.0


# SQL jadvalni yangilash va oʻchirish