# Ma'lumotlar ombori SQLite3

In [2]:
# kerakli kutubxonalarni chaqirish
import pandas as pd
import sqlite3 as sql
from pprint import pprint as print

In [3]:
# tashqi ma'lumotlar bazasidan (.scv) ma'lumotlarni olish
!wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

--2026-10-15 05:09:11--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 104.21.30.141, 172.67.172.250, 2606:4700:3033::ac43:acfa, ...
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|104.21.30.141|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.03s

2026-10-15 05:09:12 (10.4 MB/s) - ‘chinook.zip’ saved [305596/305596]

In [4]:
!unzip chinook.zip

Archive:  chinook.zip
  inflating: chinook.db

In [5]:
# DB ni o'zgaruvchiga yuklash
db = sql.connect("chinook.db")
cursor = db.cursor()

In [6]:

# fetchall metodi yordamida table ni chiqarish
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
cursor.fetchall()

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [7]:
cursor.execute("SELECT COUNT (*) FROM employees")
cursor.fetchone() # jadvaldan bitta ma'lumotni chiqarish

(8,)

In [8]:
cursor.execute("PRAGMA table_info(customers);")
cursor.fetchall()

[(0, 'CustomerId', 'INTEGER', 1, None, 1),
 (1, 'FirstName', 'NVARCHAR(40)', 1, None, 0),
 (2, 'LastName', 'NVARCHAR(20)', 1, None, 0),
 (3, 'Company', 'NVARCHAR(80)', 0, None, 0),
 (4, 'Address', 'NVARCHAR(70)', 0, None, 0),
 (5, 'City', 'NVARCHAR(40)', 0, None, 0),
 (6, 'State', 'NVARCHAR(40)', 0, None, 0),
 (7, 'Country', 'NVARCHAR(40)', 0, None, 0),
 (8, 'PostalCode', 'NVARCHAR(10)', 0, None, 0),
 (9, 'Phone', 'NVARCHAR(24)', 0, None, 0),
 (10, 'Fax', 'NVARCHAR(24)', 0, None, 0),
 (11, 'Email', 'NVARCHAR(60)', 1, None, 0),
 (12, 'SupportRepId', 'INTEGER', 0, None, 0)]

## Jadvaldan ma'lumotni chiqarish

In [9]:
cursor.execute("SELECT * FROM customers")
mijozlar = cursor.fetchmany()

In [10]:
query = "SELECT CustomerId, FirstName, LastName, Phone, Country FROM customers LIMIT 20"
df = pd.read_sql(query, db, index_col="CustomerId")
df.head()

            FirstName     LastName               Phone         Country
CustomerId
1                Luís    Gonçalves  +55 (12) 3923-5555          Brazil
2              Leonie       Köhler    +49 0711 2842222         Germany
3            François     Tremblay   +1 (514) 721-4711          Canada
4               Bjørn       Hansen     +47 22 44 22 22          Norway
5           František  Wichterlová    +420 2 4172 5555  Czech Republic

# Tartiblash (ORDER BY) va saralash (DISTINCT)

In [17]:
query = "SELECT CustomerId, FirstName, LastName, Phone, Country FROM customers ORDER BY Country LIMIT 5"
df = pd.read_sql(query, db, index_col="CustomerId")
df

           FirstName   LastName                Phone    Country
CustomerId
56             Diego  Gutiérrez  +54 (0)11 4311 4333  Argentina
55              Mark     Taylor   +61 (02) 9332 3633  Australia
7             Astrid     Gruber       +43 01 5134505    Austria
8               Daan    Peeters     +32 02 219 03 03    Belgium
1               Luís  Gonçalves   +55 (12) 3923-5555     Brazil

In [15]:
query = "SELECT DISTINCT Country FROM customers LIMIT 5"
cursor.execute(query)
cursor.fetchmany()

[('Brazil',)]

In [16]:
pd.read_sql(query, db)

          Country
0          Brazil
1         Germany
2          Canada
3          Norway
4  Czech Republic

# **Filtrlash (WHERE)**

In [14]:
query = 'SELECT * FROM customers WHERE country="Germany" AND country="USA ORDER BY LastName"'
pd.read_sql(query,db)

Empty DataFrame
Columns: [CustomerId, FirstName, LastName, Company, Address, City, State, Country, PostalCode, Phone, Fax, Email, SupportRepId]
Index: []