# Ma'lumotlar ombori SQLite3

In [1]:
# kerakli kutubxonalarni chaqirish
import pandas as pd
import sqlite3 as sql
from pprint import pprint as print

In [2]:
# tashqi ma'lumotlar bazasidan (.scv) ma'lumotlarni olish
!wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

--2026-10-14 06:08:52--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 172.67.172.250, 104.21.30.141, 2606:4700:3033::ac43:acfa, ...
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|172.67.172.250|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.04s

2026-10-14 06:08:52 (7.03 MB/s) - ‘chinook.zip’ saved [305596/305596]

In [3]:
!unzip chinook.zip

Archive:  chinook.zip
  inflating: chinook.db

In [4]:
# DB ni o'zgaruvchiga yuklash
db = sql.connect("chinook.db")
cursor = db.cursor()

In [5]:

# fetchall metodi yordamida table ni chiqarish
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
cursor.fetchall()

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [6]:
cursor.execute("SELECT COUNT (*) FROM employees")
cursor.fetchone() # jadvaldan bitta ma'lumotni chiqarish

(8,)

In [7]:
cursor.execute("PRAGMA table_info(customers);")
cursor.fetchall()

[(0, 'CustomerId', 'INTEGER', 1, None, 1),
 (1, 'FirstName', 'NVARCHAR(40)', 1, None, 0),
 (2, 'LastName', 'NVARCHAR(20)', 1, None, 0),
 (3, 'Company', 'NVARCHAR(80)', 0, None, 0),
 (4, 'Address', 'NVARCHAR(70)', 0, None, 0),
 (5, 'City', 'NVARCHAR(40)', 0, None, 0),
 (6, 'State', 'NVARCHAR(40)', 0, None, 0),
 (7, 'Country', 'NVARCHAR(40)', 0, None, 0),
 (8, 'PostalCode', 'NVARCHAR(10)', 0, None, 0),
 (9, 'Phone', 'NVARCHAR(24)', 0, None, 0),
 (10, 'Fax', 'NVARCHAR(24)', 0, None, 0),
 (11, 'Email', 'NVARCHAR(60)', 1, None, 0),
 (12, 'SupportRepId', 'INTEGER', 0, None, 0)]

## Jadvaldan ma'lumotni chiqarish

In [35]:
cursor.execute("SELECT * FROM customers")
mijozlar = cursor.fetchmany()

In [36]:
query = "SELECT CustomerId, FirstName, LastName, Phone, Country FROM customers LIMIT 20"
df = pd.read_sql(query, db, index_col="CustomerId")
df.head()

            FirstName     LastName               Phone         Country
CustomerId
1                Luís    Gonçalves  +55 (12) 3923-5555          Brazil
2              Leonie       Köhler    +49 0711 2842222         Germany
3            François     Tremblay   +1 (514) 721-4711          Canada
4               Bjørn       Hansen     +47 22 44 22 22          Norway
5           František  Wichterlová    +420 2 4172 5555  Czech Republic

# Tartiblash (ORDER BY) va saralash (DISTINCT)

In [45]:
query = "SELECT CustomerId, FirstName, LastName, Phone, Country FROM customers ORDER BY Country"
df = pd.read_sql(query, db, index_col="CustomerId")
df

            FirstName      LastName                Phone         Country
CustomerId
56              Diego     Gutiérrez  +54 (0)11 4311 4333       Argentina
55               Mark        Taylor   +61 (02) 9332 3633       Australia
7              Astrid        Gruber       +43 01 5134505         Austria
8                Daan       Peeters     +32 02 219 03 03         Belgium
1                Luís     Gonçalves   +55 (12) 3923-5555          Brazil
10            Eduardo       Martins   +55 (11) 3033-5446          Brazil
11          Alexandre         Rocha   +55 (11) 3055-3278          Brazil
12            Roberto       Almeida   +55 (21) 2271-7000          Brazil
13           Fernanda         Ramos   +55 (61) 3363-5547          Brazil
3            François      Tremblay    +1 (514) 721-4711          Canada
14               Mark       Philips    +1 (780) 434-4554          Canada
15           Jennifer      Peterson    +1 (604) 688-2255          Canada
29             Robert         Brown    +1 (416) 363-8888          Canada
30             Edward       Francis    +1 (613) 234-3322          Canada
31             Martha          Silk    +1 (902) 450-0450          Canada
32              Aaron      Mitchell    +1 (204) 452-6452          Canada
33              Ellie      Sullivan    +1 (867) 920-2233          Canada
57               Luis         Rojas    +56 (0)2 635 4444           Chile
5           František   Wichterlová     +420 2 4172 5555  Czech Republic
6              Helena          Holý     +420 2 4177 0449  Czech Republic
9                Kara       Nielsen       +453 3331 9991         Denmark
44              Terhi    Hämäläinen     +358 09 870 2000         Finland
39            Camille       Bernard   +33 01 49 70 65 65          France
40          Dominique      Lefebvre   +33 01 47 42 71 71          France
41               Marc        Dubois   +33 04 78 30 30 30          France
42              Wyatt        Girard   +33 05 56 96 96 96          France
43           Isabelle       Mercier   +33 03 80 73 66 99          France
2              Leonie        Köhler     +49 0711 2842222         Germany
36             Hannah     Schneider     +49 030 26550280         Germany
37               Fynn    Zimmermann     +49 069 40598889         Germany
38             Niklas      Schröder      +49 030 2141444         Germany
45           Ladislav        Kovács                 None         Hungary
58              Manoj        Pareek    +91 0124 39883988           India
59               Puja    Srivastava     +91 080 22289999           India
46               Hugh      O'Reilly      +353 01 6792424         Ireland
47              Lucas       Mancini      +39 06 39733434           Italy
48           Johannes  Van der Berg      +31 020 6223130     Netherlands
4               Bjørn        Hansen      +47 22 44 22 22          Norway
49          Stanisław        Wójcik     +48 22 828 37 39          Poland
34               João     Fernandes   +351 (213) 466-111        Portugal
35           Madalena       Sampaio   +351 (225) 022-448        Portugal
50            Enrique         Muñoz      +34 914 454 454           Spain
51             Joakim     Johansson     +46 08-651 52 52          Sweden
16              Frank        Harris    +1 (650) 253-0000             USA
17               Jack         Smith    +1 (425) 882-8080             USA
18           Michelle        Brooks    +1 (212) 221-3546             USA
19                Tim         Goyer    +1 (408) 996-1010             USA
20                Dan        Miller    +1 (650) 644-3358             USA
21              Kathy         Chase    +1 (775) 223-7665             USA
22            Heather       Leacock    +1 (407) 999-7788             USA
23               John        Gordon    +1 (617) 522-1333             USA
24              Frank       Ralston    +1 (312) 332-3232             USA
25             Victor       Stevens    +1 (608) 257-0597             USA
26            Richard    Cunningham    +1 (817) 924-7272             USA
27            Patrick          Gray    +1 (520) 622-4200             USA
28              Julia       Barnett    +1 (801) 531-7272             USA
52               Emma         Jones    +44 020 7707 0707  United Kingdom
53               Phil        Hughes    +44 020 7976 5722  United Kingdom
54              Steve        Murray    +44 0131 315 3300  United Kingdom

In [50]:
query = "SELECT DISTINCT Country FROM customers"
cursor.execute(query)
cursor.fetchmany()

[('Brazil',)]

In [48]:
pd.read_sql(query, db)

           Country
0           Brazil
1          Germany
2           Canada
3           Norway
4   Czech Republic
5          Austria
6          Belgium
7          Denmark
8              USA
9         Portugal
10          France
11         Finland
12         Hungary
13         Ireland
14           Italy
15     Netherlands
16          Poland
17           Spain
18          Sweden
19  United Kingdom
20       Australia
21       Argentina
22           Chile
23           India

# **Filtrlash (WHERE)**

In [58]:
query = 'SELECT * FROM customers WHERE country="Germany" AND country="USA ORDER BY LastName"'
pd.read_sql(query,db)

Empty DataFrame
Columns: [CustomerId, FirstName, LastName, Company, Address, City, State, Country, PostalCode, Phone, Fax, Email, SupportRepId]
Index: []